### ISSUE TITLE
Need pixels only

### ISSUE THREAD

**Issue by YakoArt** [romashamin/Size-Marks-PS#25]
Hi!
I use the CS 6(v.13.1.2) and SM.jsx-v1.0. Everything works perfectly. But the script shows both sizes. I need pixels only. How to hide the first size (pt)?
![00notneed](https://cloud.githubusercontent.com/assets/15941362/12773000/63d04082-ca61-11e5-8771-95b24d23953a.jpg)

**Comment by romashamin** [comment]
@YakoArt the script prints pixels for 72 ppi documents and pixels + points for non-72 ones, so use 72 ppi for your document.

**Comment by YakoArt** [comment]
oops!.. overlooked. Thanks!
