### ISSUE TITLE
Scaled units

### ISSUE THREAD

**Issue by cballenar** [romashamin/Size-Marks-PS#26]
I'm confused by what Scaled Units are for. I see that they convert the target to points using the document resolution but I'm failing to understand how that's helpful, to me, at least (?).

**Comment by romashamin** [comment]
@cballenar I don’t know what are you doing at work. The feature is useful for guys that are making design for mobile phones.

**Comment by cballenar** [comment]
Wow... What a useful answer... Thanks...
