### ISSUE TITLE
pt/px

### ISSUE THREAD

**Issue by cesar-mso** [romashamin/Size-Marks-PS#30]
Hi!

Thank you for a great plug-in! Just wanted to know if there's a way to toggle off the "pt" size amount and only have "px"? The gif image on the info page shows only px in use but I just installed it and tried it out but I get sizes listed as "101.6 pt / 144 px", and I only need px.

Thank you in advance!

**Comment by romashamin** [comment]
@cesar-mso take a look at [‘Need pixels only’ issue](https://github.com/romashamin/Size-Marks-PS/issues/25).

**Comment by cesar-mso** [comment]
Thank you and apologies for that, will make sure to check through the closed section before posting!!
