### ISSUE TITLE
Стиль

### ISSUE THREAD

**Issue by murad7506** [romashamin/Size-Marks-PS#36]
Здравствуйте! Как сделать:
1. Что бы размеры отображались в миллиметрах или сантиметрах?
2. Как изменить размер шрифта (например при высоком разрешении, очень мелкий текст размеров получается)?
3. Как менять цвета текста и линий?
4. Стиль линий (пунктир)?

**Comment by romashamin** [comment]
@murad7506 
1. Никак.
2. Никак.
3. Измените foreground color — главный цвет, заданный на панели инструментов.
4. Измените стиль инструмента Pencil tool.

**Comment by murad7506** [comment]
Спасибо!
